name: Docker hub push with latest image, Kubernetes cluster upgrade

on:
  push:
    branches: master

jobs:
  eshop-spring-boot:
    name: E-Shop docker image push to docker hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./web/src/main/docker/
          file: ./web/src/main/docker/Dockerfile
          push: true
          tags: bojanp1801/eshop-spring-boot:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}


  eshop-helm-kubernetes:
   name: Helm release update for the e-shop app
   runs-on: ubuntu-latest
   needs: [eshop-spring-boot, pg-database-kubernetes, prometheus-kubernetes]
 
   steps:
     - uses: actions/checkout@v2
     - name: Helm upgrade or install
       uses: WyriHaximus/github-action-helm3@v2
       with:
         exec: helm upgrade --install eshop-spring-boot ./helm-charts/eshop-application
         kubeconfig: '${{ secrets.KUBECONFIG }}'


  pg-database-kubernetes:
   name: Pod update for the PGDB
   runs-on: ubuntu-latest
 
   steps:
     - uses: actions/checkout@v2
     - name: Apply with kubectl
       uses: danielr1996/kubectl-action@1.0.0
       with:
         exec: kubectl apply -f ./kubernetes-cluster/eshop-postgres
         kubeconfig: '${{ secrets.KUBECONFIG }}'


  prometheus-kubernetes:
   name: Helm release update for Prometheus
   runs-on: ubuntu-latest
 
   steps:
     - uses: actions/checkout@v2
     - name: Helm upgrade or install
       uses: WyriHaximus/github-action-helm3@v2
       with:
         exec: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm upgrade --install prometheus bitnami/kube-prometheus
         kubeconfig: '${{ secrets.KUBECONFIG }}'